/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminKirishRouteImport } from './routes/admin-kirish'
import { Route as BuyurtmalarimRouteImport } from './routes/buyurtmalarim'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as KirishRouteImport } from './routes/kirish'
import { Route as SavatRouteImport } from './routes/savat'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBuyurtmalarRouteImport } from './routes/admin.buyurtmalar'
import { Route as AdminMahsulotlarRouteImport } from './routes/admin.mahsulotlar'
import { Route as AdminMijozlarRouteImport } from './routes/admin.mijozlar'
import { Route as AdminSozlamalarRouteImport } from './routes/admin.sozlamalar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKirishRoute = AdminKirishRouteImport.update({
  id: '/admin-kirish',
  path: '/admin-kirish',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyurtmalarimRoute = BuyurtmalarimRouteImport.update({
  id: '/buyurtmalarim',
  path: '/buyurtmalarim',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const KirishRoute = KirishRouteImport.update({
  id: '/kirish',
  path: '/kirish',
  getParentRoute: () => rootRouteImport,
} as any)
const SavatRoute = SavatRouteImport.update({
  id: '/savat',
  path: '/savat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuyurtmalarRoute = AdminBuyurtmalarRouteImport.update({
  id: '/buyurtmalar',
  path: '/buyurtmalar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMahsulotlarRoute = AdminMahsulotlarRouteImport.update({
  id: '/mahsulotlar',
  path: '/mahsulotlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMijozlarRoute = AdminMijozlarRouteImport.update({
  id: '/mijozlar',
  path: '/mijozlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSozlamalarRoute = AdminSozlamalarRouteImport.update({
  id: '/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-kirish': typeof AdminKirishRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/katalog': typeof KatalogRoute
  '/kirish': typeof KirishRoute
  '/savat': typeof SavatRoute
  '/admin/buyurtmalar': typeof AdminBuyurtmalarRoute
  '/admin/mahsulotlar': typeof AdminMahsulotlarRoute
  '/admin/mijozlar': typeof AdminMijozlarRoute
  '/admin/sozlamalar': typeof AdminSozlamalarRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-kirish': typeof AdminKirishRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/katalog': typeof KatalogRoute
  '/kirish': typeof KirishRoute
  '/savat': typeof SavatRoute
  '/admin/buyurtmalar': typeof AdminBuyurtmalarRoute
  '/admin/mahsulotlar': typeof AdminMahsulotlarRoute
  '/admin/mijozlar': typeof AdminMijozlarRoute
  '/admin/sozlamalar': typeof AdminSozlamalarRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-kirish': typeof AdminKirishRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/katalog': typeof KatalogRoute
  '/kirish': typeof KirishRoute
  '/savat': typeof SavatRoute
  '/admin/buyurtmalar': typeof AdminBuyurtmalarRoute
  '/admin/mahsulotlar': typeof AdminMahsulotlarRoute
  '/admin/mijozlar': typeof AdminMijozlarRoute
  '/admin/sozlamalar': typeof AdminSozlamalarRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-kirish'
    | '/buyurtmalarim'
    | '/katalog'
    | '/kirish'
    | '/savat'
    | '/admin/buyurtmalar'
    | '/admin/mahsulotlar'
    | '/admin/mijozlar'
    | '/admin/sozlamalar'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-kirish'
    | '/buyurtmalarim'
    | '/katalog'
    | '/kirish'
    | '/savat'
    | '/admin/buyurtmalar'
    | '/admin/mahsulotlar'
    | '/admin/mijozlar'
    | '/admin/sozlamalar'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-kirish'
    | '/buyurtmalarim'
    | '/katalog'
    | '/kirish'
    | '/savat'
    | '/admin/buyurtmalar'
    | '/admin/mahsulotlar'
    | '/admin/mijozlar'
    | '/admin/sozlamalar'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminKirishRoute: typeof AdminKirishRoute
  BuyurtmalarimRoute: typeof BuyurtmalarimRoute
  KatalogRoute: typeof KatalogRoute
  KirishRoute: typeof KirishRoute
  SavatRoute: typeof SavatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-kirish': {
      id: '/admin-kirish'
      path: '/admin-kirish'
      fullPath: '/admin-kirish'
      preLoaderRoute: typeof AdminKirishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyurtmalarim': {
      id: '/buyurtmalarim'
      path: '/buyurtmalarim'
      fullPath: '/buyurtmalarim'
      preLoaderRoute: typeof BuyurtmalarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirish': {
      id: '/kirish'
      path: '/kirish'
      fullPath: '/kirish'
      preLoaderRoute: typeof KirishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savat': {
      id: '/savat'
      path: '/savat'
      fullPath: '/savat'
      preLoaderRoute: typeof SavatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buyurtmalar': {
      id: '/admin/buyurtmalar'
      path: '/buyurtmalar'
      fullPath: '/admin/buyurtmalar'
      preLoaderRoute: typeof AdminBuyurtmalarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mahsulotlar': {
      id: '/admin/mahsulotlar'
      path: '/mahsulotlar'
      fullPath: '/admin/mahsulotlar'
      preLoaderRoute: typeof AdminMahsulotlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mijozlar': {
      id: '/admin/mijozlar'
      path: '/mijozlar'
      fullPath: '/admin/mijozlar'
      preLoaderRoute: typeof AdminMijozlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sozlamalar': {
      id: '/admin/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/admin/sozlamalar'
      preLoaderRoute: typeof AdminSozlamalarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBuyurtmalarRoute: typeof AdminBuyurtmalarRoute
  AdminMahsulotlarRoute: typeof AdminMahsulotlarRoute
  AdminMijozlarRoute: typeof AdminMijozlarRoute
  AdminSozlamalarRoute: typeof AdminSozlamalarRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuyurtmalarRoute: AdminBuyurtmalarRoute,
  AdminMahsulotlarRoute: AdminMahsulotlarRoute,
  AdminMijozlarRoute: AdminMijozlarRoute,
  AdminSozlamalarRoute: AdminSozlamalarRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminKirishRoute: AdminKirishRoute,
  BuyurtmalarimRoute: BuyurtmalarimRoute,
  KatalogRoute: KatalogRoute,
  KirishRoute: KirishRoute,
  SavatRoute: SavatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
