/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuyurtmalarimRouteImport } from './routes/buyurtmalarim'
import { Route as KirishRouteImport } from './routes/kirish'
import { Route as SavatRouteImport } from './routes/savat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyurtmalarimRoute = BuyurtmalarimRouteImport.update({
  id: '/buyurtmalarim',
  path: '/buyurtmalarim',
  getParentRoute: () => rootRouteImport,
} as any)
const KirishRoute = KirishRouteImport.update({
  id: '/kirish',
  path: '/kirish',
  getParentRoute: () => rootRouteImport,
} as any)
const SavatRoute = SavatRouteImport.update({
  id: '/savat',
  path: '/savat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/kirish': typeof KirishRoute
  '/savat': typeof SavatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/kirish': typeof KirishRoute
  '/savat': typeof SavatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/kirish': typeof KirishRoute
  '/savat': typeof SavatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/buyurtmalarim' | '/kirish' | '/savat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/buyurtmalarim' | '/kirish' | '/savat'
  id: '__root__' | '/' | '/admin' | '/buyurtmalarim' | '/kirish' | '/savat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuyurtmalarimRoute: typeof BuyurtmalarimRoute
  KirishRoute: typeof KirishRoute
  SavatRoute: typeof SavatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyurtmalarim': {
      id: '/buyurtmalarim'
      path: '/buyurtmalarim'
      fullPath: '/buyurtmalarim'
      preLoaderRoute: typeof BuyurtmalarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirish': {
      id: '/kirish'
      path: '/kirish'
      fullPath: '/kirish'
      preLoaderRoute: typeof KirishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savat': {
      id: '/savat'
      path: '/savat'
      fullPath: '/savat'
      preLoaderRoute: typeof SavatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuyurtmalarimRoute: BuyurtmalarimRoute,
  KirishRoute: KirishRoute,
  SavatRoute: SavatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
